[package]
name = "lsplit"
version = "0.1.0"
authors = ["Cliff Spital <cspital@uw.edu>"]

[dependencies]

[dependencies.clap]
version = "~2.32.0"
default-features = false
features = ["suggestions", "wrap_help"]
